---
name: Bundle and Deploy EAS Update

on:
  push:
    branches:
      - hailey/expo-updates
  release:
    types:
      - published

jobs:
  bundleDeploy:
    name: Bundle and Deploy EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: ⚙️ Install Dependencies
        run: yarn install

      - name: 🪛 Install jq
        uses: dcarbone/install-jq-action@v2

      - name: ⛏️ Setup Expo
        run: yarn global add eas-cli-local-build-plugin

      - name: 🔤 Compile Translations
        run: yarn intl:build

      - name: ✏️ Write environment variables
        run: |
          export json='${{ secrets.GOOGLE_SERVICES_TOKEN }}'
          echo "${{ secrets.ENV_TOKEN }}" > .env
          echo "$json" > google-services.json

      - name: 🏗️ Create Bundle
        run: yarn export

      - name: 📦 Package Bundle and 🚀 Deploy
        run: yarn make-deploy-bundle
