name: Deploy Nightly Testflight Release

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    name: Deploy Nightly Testflight Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: EAS build and submit
        run: yarn use-build-number eas build -p ios --profile github --non-interactive
