name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Lint Action
        uses: wearerequired/lint-action@v2.2.0
        with:
          eslint: true
          prettier: true
      - name: Lint
        run: yarn lint
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Run tests
        run: | 
          yarn test-ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: junit.xml    # Path to test results
          reporter: jest-junit        # Format of test results
      - name: Run tests
        run: | 
          yarn test --forceExit
